### ISSUE TITLE
401 签名错误，请检查后再试

### ISSUE THREAD

**Issue by MidnightDJ** [yansongda/hyperf-pay#10]
**经过postman测试和微信签名工具检测，应该是签名算法无法正确签名。**  
**期待作者能回复一下是怎么回事**

<img width="344" alt="1636802221(1)" src="https://user-images.githubusercontent.com/23242278/141635641-52344d2d-169a-41d9-a26c-e6111798c289.png">
<img width="477" alt="1636802253(1)" src="https://user-images.githubusercontent.com/23242278/141635994-b08ac89b-1e8a-4eac-81ee-c26c46e394a2.png">

**Comment by yansongda** [comment]
自己检查下相关配置参数吧
