### ISSUE TITLE
公众号支付，预下单，log出现预下单失败：响应缺少 prepay_id 参数

### ISSUE THREAD

**Issue by sinceyy** [yansongda/hyperf-pay#12]
按提示与微信官方提示报错，在使用_force强制替换了config配置，如下
weixin => [default=>[
                    'mp_app_id'                => 'xxx',
                    'mch_secret_key'       => 'xxx',
                    'mch_secret_cert'      => '/Users/lianka/Project/payCenter/app/Core/Cert/apiclient_key.pem',
                    'mch_public_cert_path' => '/Users/lianka/Project/payCenter/app/Core/Cert/apiclient_cert.pem',
                    'mch_id'                   => 'xx',
                    'sub_mch_id'           => 'xx',
                    'notify_url'               => 'https://yansongda.cn/wechat/notify',

]]

增加参数sub_mch_id后，此报错依旧。想知道是传参方式有问题还是sub_mch_id字段名问题

**Comment by yansongda** [comment]
配置发全，代码发全

**Comment by sinceyy** [comment]
`
$config = [
    'alipay' => [
        'default' => [
            // 支付宝分配的 app_id
            'app_id'                  => '',
            // 应用私钥
            'app_secret_cert'         => '',
            // 应用公钥证书 路径
            'app_public_cert_path'    => '',
            // 支付宝公钥证书 路径
            'alipay_public_cert_path' => '',
            // 支付宝根证书 路径
            'alipay_root_cert_path'   => '',
            'return_url'              => '',
            'notify_url'              => '',
            'mode'                    => Pay::MODE_NORMAL,
        ],
    ],
    'wechat' => [
        'default' => [
            // 公众号 的 app_id
            'mp_app_id'               => '',
            // 小程序 的 app_id
            'mini_app_id'             => '',
            // app 的 app_id
            'app_id'                  => '',
            // 商户号
            'mch_id'                  => '',
            // 二级商户
            'sub_mch_id'              => '',
            // 合单 app_id
            'combine_app_id'          => '',
            // 合单商户号
            'combine_mch_id'          => '',
            // 商户秘钥
            'mch_secret_key'          => '',
            // 商户私钥
            'mch_secret_cert'         => '',
            // 商户公钥证书路径
            'mch_public_cert_path'    => '',
            // 微信公钥证书路径
            'wechat_public_cert_path' => '',
            'mode'                    => Pay::MODE_NORMAL,
        ],
    ],
    'http'   => [ // optional
        'timeout'         => 5.0,
        'connect_timeout' => 5.0,
        // 更多配置项请参考 [Guzzle](https://guzzle-cn.readthedocs.io/zh_CN/latest/request-options.html)
    ],
    'logger' => [
        'enable'   => true,
        'file'     => BASE_PATH . '/runtime/logs/pay.log',
        'level'    => 'debug',  // 建议生产环境等级调整为 info，开发环境为 debug
        'type'     => 'single', // optional, 可选 daily.
        'max_file' => 30,       // optional, 当 type 为 daily 时有效，默认 30 天
    ],
];
`

$orderData = [
            'out_trade_no' => time().‘2021112901’,
            'description' => '这是测试的支付',
            'amount' => [
                'total' => 1,
                'currency' => 'CNY',
            ],
            'payer' => [
                'openid' => ‘’,
            ]
        ];


$handler = container()->get(Pay::class);
$this->order = $handler->wechat($config)->mp($orderData);


2021-11-29T06:26:59.964777+00:00 > yansongda.pay.ERROR > [wechat][InvokePrepayPlugin] 预下单失败：响应缺少 prepay_id 参数，请自行检查参数是否符合微信要求 {"code":"PARAM_ERROR","message":"受理机构必须传入sub_mch_id"}

**Comment by yansongda** [comment]
你是供应商么？是供应商的话， mode 参数得配置成 Pay::MODE_SERVICE

**Comment by sinceyy** [comment]
服务商的

**Comment by sinceyy** [comment]
Pay::MODE_SERVICE这个也试过，返回的是同样的

**Comment by sinceyy** [comment]
你那里测试可以吗？

**Comment by yansongda** [comment]
你检查下你自己的配置吧，99% 的问题都是 配置问题，自己调试下看看

如果你看 readme 进行处理的话，hyperf 版本读取的是 config/autoload/pay.php 这个配置文件

**Comment by sinceyy** [comment]
这个我晓得是pay配置文件，但是配置上，唯独就加了sub_mch_id 参数，其他没动任何

**Comment by sinceyy** [comment]
而且，我如果使用原包，Yansongda\Pay\Pay 这个类去调用时候，返回的是[222] in /Users/lianka/Project/payCenter/vendor/yansongda/pay/src/Functions.php

**Comment by sinceyy** [comment]
使用命令生成的config/autoload/pay.php 这个配置文件与你官网 的文档中的pay文件不一样。生成的pay文件中没有
sub_mch_id等字段，官网文档事例中有，按官网事例的内容覆盖到本地的pay文件后，没有报预下单失败：响应缺少 prepay_id 参数这个错误了，但是同时报错缺少payer中缺少openid，但其实是有传的，跟你文档中是一样的
