### ISSUE TITLE
证书配置能支持字符串吗

### ISSUE THREAD

**Issue by fushiliang321** [yansongda/hyperf-pay#13]
有些情况下我们希望证书的配置能直接通过后台以字符串的方式进行动态配置的，现在只能传文件，后面如果要更换证书的话就不方便了

**Comment by yansongda** [comment]
哪个证书？私钥证书是可以字符串的

**Comment by fushiliang321** [comment]
两个公钥证书和根证书，现在只能用路径的方式。

**Comment by yansongda** [comment]
> 两个公钥证书和根证书，现在只能用路径的方式。

内容太多了，字符串的形式也不现实

**Comment by fushiliang321** [comment]
官方的sdk都支持用字符串，怎么会不现实呢？

**Comment by yansongda** [comment]
哪里？有 链接 示例么？

**Comment by fushiliang321** [comment]
https://github.com/alipay/alipay-easysdk/tree/066388d02c6f55fe0919d75b386456d80801fec2/php     非证书模式

**Comment by yansongda** [comment]
。。。

如果你要用非证书模式，请用   yansongda/pay v2 版本：https://github.com/yansongda/pay/tree/v2

v3 版本只支持证书模式，非证书模式目前有很多限制，后面会被淘汰
