### ISSUE TITLE
hyperf里面调用什么都不提示都报错这个咋回事

### ISSUE THREAD

**Issue by fengyikang88** [yansongda/hyperf-pay#20]
[ERROR] Yansongda\Pay\Exception\InvalidResponseException: (5003) in /www/wwwroot/wash/apiadminHf/vendor/yansongda/pay/src/Functions.php:204
Stack trace:
#0 /www/wwwroot/wash/apiadminHf/vendor/yansongda/pay/src/Plugin/Wechat/LaunchPlugin.php(32): verify_wechat_sign()
#1 /www/wwwroot/wash/apiadminHf/vendor/yansongda/supports/src/Pipeline.php(126): Yansongda\Pay\Plugin\Wechat\LaunchPlugin->assembly()
#2 /www/wwwroot/.com/wash/apiadminHf/vendor/yansongda/pay/src/Plugin/Wechat/SignPlugin.php(49): Yansongda\Supports\Pipeline->Yansongda\Supports\{closure}()
#3 /www/wwwroot/.com/wash/apiadminHf/vendor/yansongda/supports/src/Pipeline.php(126): Yansongda\Pay\Plugin\Wechat\SignPlugin->assembly()

**Comment by JiYang1028** [comment]
同样问题  支付宝扫码支付出现的

**Comment by yansongda** [comment]
99% 都是配置问题

在 yansongda/pay 里按格式提 issue 吧
