### ISSUE TITLE
force 配置之后 发现不能使用hyperf的日志系统

### ISSUE THREAD

**Issue by zhufq** [yansongda/hyperf-pay#23]
public function __construct(ContainerInterface $container)
    {
        $this->config = $container->get(ConfigInterface::class)->get('pay', []);
        $this->container = $container;

        
        BigPay::config($this->config);

        $this->bootstrapHttpClient();
        $this->bootstrapLogger();
        $this->bootstrapEvent();
    }

     force 配置之后 没有机会给Pay::set 日志系统了   有没有什么好的解决方案呢？

**Comment by yansongda** [comment]
既然用了 hyperf-pay 为啥要 force 呢？啥场景？
