### ISSUE TITLE
Hyperf2.2版本

### ISSUE THREAD

**Issue by laohekou** [yansongda/hyperf-pay#3]
![image](https://user-images.githubusercontent.com/32082656/127302833-7e005d69-81c0-4445-9316-bfbd4bed8b92.png)

**Comment by yansongda** [comment]
麻烦 composer.json 发一下我看看

**Comment by laohekou** [comment]
@yansongda 
{
    "name": "hyperf/hyperf-skeleton",
    "type": "project",
    "keywords": [
        "php",
        "swoole",
        "framework",
        "hyperf",
        "microservice",
        "middleware"
    ],
    "description": "A coroutine framework that focuses on hyperspeed and flexible, specifically use for build microservices and middlewares.",
    "license": "Apache-2.0",
    "require": {
        "php": ">=7.4",
        "96qbhy/hyperf-auth": "^2.4",
        "aliyuncs/oss-sdk-php": "^2.4",
        "hyperf/async-queue": "~2.2.0",
        "hyperf/cache": "~2.2.0",
        "hyperf/command": "~2.2.0",
        "hyperf/config": "~2.2.0",
        "hyperf/constants": "~2.2.0",
        "hyperf/crontab": "^2.2",
        "hyperf/database": "~2.2.0",
        "hyperf/db-connection": "~2.2.0",
        "hyperf/event": "^2.2",
        "hyperf/framework": "~2.2.0",
        "hyperf/guzzle": "~2.2.0",
        "hyperf/http-server": "~2.2.0",
        "hyperf/json-rpc": "~2.2.0",
        "hyperf/logger": "~2.2.0",
        "hyperf/memory": "~2.2.0",
        "hyperf/model-cache": "~2.2.0",
        "hyperf/phar": "^2.2",
        "hyperf/pool": "^2.2",
        "hyperf/process": "~2.2.0",
        "hyperf/redis": "~2.2.0",
        "hyperf/rpc": "~2.2.0",
        "hyperf/rpc-client": "~2.2.0",
        "hyperf/rpc-server": "~2.2.0",
        "hyperf/session": "^2.2",
        "hyperf/signal": "^2.2",
        "hyperf/snowflake": "^2.2",
        "hyperf/task": "^2.2",
        "hyperf/tracer": "^2.2",
        "hyperf/validation": "^2.2",
        "hyperf/watcher": "^2.2",
        "overtrue/wechat": "~5.0",
        "reasno/swoole-aliyunoss-addon": "^1.0",
        "yurunsoft/pay-sdk": "^3.1",
        "yurunsoft/yurun-oauth-login": "^3.0"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "^2.14",
        "hyperf/devtool": "~2.2.0",
        "hyperf/testing": "~2.2.0",
        "mockery/mockery": "^1.0",
        "phpstan/phpstan": "^0.12",
        "swoole/ide-helper": "^4.5"
    },
    "suggest": {
        "ext-openssl": "Required to use HTTPS.",
        "ext-json": "Required to use JSON.",
        "ext-pdo": "Required to use MySQL Client.",
        "ext-pdo_mysql": "Required to use MySQL Client.",
        "ext-redis": "Required to use Redis Client."
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "files": []
    },
    "autoload-dev": {
        "psr-4": {
            "HyperfTest\\": "./test/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "optimize-autoloader": true,
        "sort-packages": true
    },
    "extra": [],
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-autoload-dump": [
            "rm -rf runtime/container"
        ],
        "test": "co-phpunit -c phpunit.xml --colors=always",
        "cs-fix": "php-cs-fixer fix $1",
        "analyse": "phpstan analyse --memory-limit 300M -l 0 -c phpstan.neon ./app ./config",
        "start": [
            "Composer\\Config::disableProcessTimeout",
            "php ./bin/hyperf.php start"
        ]
    }
}

**Comment by yansongda** [comment]
有用到这么多包么？

**Comment by laohekou** [comment]
@yansongda  跟这个包有关系？
![image](https://user-images.githubusercontent.com/32082656/127417009-b8d795ff-76d8-4b97-b3aa-f3551cf014e8.png)

**Comment by yansongda** [comment]
这么多包，应该不是正式的项目吧？

**Comment by laohekou** [comment]
@yansongda  新项目启动，提前都给装了。

**Comment by yansongda** [comment]
可以使用 `composer require yansongda/hyperf-pay -W` 安装

**Comment by laohekou** [comment]
@yansongda  谢谢。
