### ISSUE TITLE
psr/container 包版本兼容，能解决吗

### ISSUE THREAD

**Issue by laohekou** [yansongda/hyperf-pay#4]
![image](https://user-images.githubusercontent.com/32082656/127625466-166bdb8e-15c4-4d3f-8c60-1921f25d3731.png)

**Comment by yansongda** [comment]
Pay 项目兼容  psr/container 的 1.1 和 2.0 版本，你这个应该是其它的包不兼容 psr/container 2.0 版本导致降级的

不影响使用

**Comment by yansongda** [comment]
1.1.0 版本已兼容
