### ISSUE TITLE
PHP 8+hyperf2.2  签名错误,请检查后再试

### ISSUE THREAD

**Issue by MidnightDJ** [yansongda/hyperf-pay#8]
无法获取到$timestamp  $random  $body 这三个值 ，var_dump 为空，
请问一下是什么问题？
<img width="511" alt="1636704953(1)" src="https://user-images.githubusercontent.com/23242278/141433638-380343f7-9c09-48a6-b5b4-dda2836db718.png">
<img width="532" alt="1636705072(1)" src="https://user-images.githubusercontent.com/23242278/141433933-95b0190e-9ffc-4dfb-8bea-cb2fdb5932df.png">
<img width="629" alt="1636705193(1)" src="https://user-images.githubusercontent.com/23242278/141434195-b2a0c3d4-c8cd-49db-8113-3a91591cf259.png">

**Comment by yansongda** [comment]
https://pay.yansongda.cn/docs/v3/wechat/callback.html#%E5%8F%82%E6%95%B0

**Comment by MidnightDJ** [comment]
看了您的建议，是在接受回调时候传入ServerRequestInterface 。
可是，我的这个问题时出现在发起支付的时候。
下面是我的代码
 
public function index(RequestInterface $request, ResponseInterface $response, Pay $pay)  

    {
        return $pay->wechat()->mp([
            'out_trade_no' => time().'',
            'description' => 'subject-测试',
            'amount' => [
                'total' => 1,
            ],
            'payer' => [
                'openid' => 'oNjG55yawDfVOLsXGLvuNyD-QIZw',
            ],
        ])->callback($request);
    }  

public function notify(RequestInterface $request, ResponseInterface $response, Pay $pay)  
   {
        $result = $pay->wechat()->callback;
    }

**Comment by MidnightDJ** [comment]
@yansongda 
问题是为什么这个函数里获取不到参数呢？
![image](https://user-images.githubusercontent.com/23242278/141484393-35e83718-399b-4feb-8887-1ce970e5f539.png)
